### ISSUE TITLE
Add Hamburger menu in navbar

### ISSUE THREAD

**Issue by itshypon** [DCRUSTODC/iic-client#2]
Temporarily font is decreased for smaller screen but add hamburger in navbar for smaller screen.

**Comment by Vaishali785** [comment]
Hi @itshypon, I'd like to contribute here. Can you please assign this to me?

**Comment by itshypon** [comment]
@Vaishali785 Assigned

**Comment by Vaishali785** [comment]
> @Vaishali785 Assigned

Thanks. I'm working on it.

**Comment by Vaishali785** [comment]
Hi @itshypon, can you please tell me what are you using for CSS? And is it okay if I use pure css for hamburger menu?

**Comment by itshypon** [comment]
@Vaishali785 I am using Tailwind here and it is recommended to use Tailwind for code quality. It will also help you learn Tailwind and get comfortable with it.

**Comment by Vaishali785** [comment]
> @Vaishali785 I am using Tailwind here and it is recommended to use Tailwind for code quality. It will also help you learn Tailwind and get comfortable with it.

Sure. I'll use the same.

**Comment by Vaishali785** [comment]
@itshypon Please review my PR and merge it.
