### ISSUE TITLE
Footer Improvement

### ISSUE THREAD

**Issue by AndrickSilva** [DCRUSTODC/iic-client#5]
Hi, 
This website looks cool but the footer can be improved more and I would like to do it.
Can you assign me this issue?

Here is the design
![image](https://github.com/DCRUSTODC/iic-client/assets/94364805/d27dee58-79aa-4eb2-9b14-c00fee063efb)

Responsive
![image](https://github.com/DCRUSTODC/iic-client/assets/94364805/f164589b-4b1c-4549-b9d3-cd3d002ef92a)

Hope you like it 
Thanks

**Comment by sambhavsaxena** [comment]
@AndrickSilva go for it

**Comment by AndrickSilva** [comment]
Hi @sambhavsaxena, 
I have created the PR please review and merge the changes
Thanks

**Comment by sambhavsaxena** [comment]
fixed #6
